module.exports = {
  experimental: {},
  future: {},
  darkMode: "class",
  important: true,
  purge: {
    enabled: process.env.TAILWIND_MODE === "build",
    content: ["./src/**/*.{html,scss,ts}"],
    options: {
      safelist: {
        standard: ["dark"],
        deep: [/^theme/, /^mat/],
      },
    },
  },

  variants: {
    accessibility: [],
    alignContent: ["responsive"],
    alignItems: ["responsive"],
    alignSelf: ["responsive"],
    animation: [],
    backgroundAttachment: [],
    backgroundClip: [],
    backgroundColor: ["dark", "responsive", "group-hover", "hover", "focus", "focus-within"],
    backgroundImage: [],
    backgroundOpacity: ["dark", "hover"],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ["dark", "group-hover", "hover", "focus", "focus-within"],
    borderOpacity: ["group-hover", "hover"],
    borderRadius: ["responsive"],
    borderStyle: [],
    borderWidth: ["dark", "responsive", "first", "last", "odd", "even"],
    boxShadow: ["dark", "responsive", "hover", "focus-within"],
    boxSizing: [],
    cursor: [],
    display: ["dark", "responsive", "hover", "group-hover"],
    divideColor: ["dark"],
    divideOpacity: [],
    divideStyle: [],
    divideWidth: ["responsive"],
    fill: [],
    flex: ["responsive"],
    flexDirection: ["responsive"],
    flexGrow: ["responsive"],
    flexShrink: ["responsive"],
    flexWrap: ["responsive"],
    fontFamily: [],
    fontSize: ["responsive"],
    fontSmoothing: [],
    fontStyle: ["responsive"],
    fontVariantNumeric: [],
    fontWeight: ["responsive"],
    gap: ["responsive"],
    gridAutoColumns: ["responsive"],
    gridAutoFlow: ["responsive"],
    gridAutoRows: ["responsive"],
    gridColumn: ["responsive"],
    gridColumnEnd: ["responsive"],
    gridColumnStart: ["responsive"],
    gridRow: ["responsive"],
    gridRowEnd: ["responsive"],
    gridRowStart: ["responsive"],
    gridTemplateColumns: ["responsive"],
    gridTemplateRows: ["responsive"],
    height: ["responsive"],
    inset: ["responsive"],
    justifyContent: ["responsive"],
    justifyItems: ["responsive"],
    justifySelf: ["responsive"],
    letterSpacing: ["responsive"],
    lineHeight: ["responsive"],
    listStylePosition: [],
    listStyleType: [],
    margin: ["responsive"],
    maxHeight: ["responsive"],
    maxWidth: ["responsive"],
    minHeight: ["responsive"],
    minWidth: ["responsive"],
    objectFit: ["responsive"],
    objectPosition: ["responsive"],
    opacity: ["responsive", "group-hover", "hover"],
    order: ["responsive"],
    outline: [],
    overflow: ["responsive"],
    overscrollBehavior: ["responsive"],
    padding: ["responsive"],
    placeContent: ["responsive"],
    placeItems: ["responsive"],
    placeSelf: ["responsive"],
    pointerEvents: ["responsive"],
    position: ["responsive"],
    resize: [],
    ringColor: ["dark", "group-hover"],
    ringOffsetColor: ["dark"],
    ringOffsetWidth: [],
    ringOpacity: [],
    ringWidth: [],
    rotate: [],
    scale: [],
    skew: [],
    space: ["responsive"],
    stroke: ["responsive"],
    strokeWidth: ["responsive"],
    tableLayout: ["responsive"],
    textAlign: ["responsive"],
    textColor: ["dark", "group-hover", "hover"],
    textDecoration: ["group-hover", "hover"],
    textOpacity: ["group-hover", "hover"],
    textOverflow: ["responsive"],
    textTransform: [],
    transform: [],
    transformOrigin: [],
    transitionDelay: [],
    transitionDuration: [],
    transitionProperty: [],
    transitionTimingFunction: [],
    translate: ["responsive", "hover"],
    userSelect: ["responsive"],
    visibility: ["responsive"],
    whitespace: ["responsive"],
    width: ["responsive"],
    wordBreak: ["responsive"],
    zIndex: ["responsive"],
  },
  corePlugins: {
    appearance: false,
    gradientColorStops: false,
    container: false,
    float: false,
    clear: false,
    placeholderColor: false,
    placeholderOpacity: false,
    verticalAlign: false,
  },

  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
};
